logging.level.root: error
logging.level.zipkin2: debug
logging.level.org.ileler: debug
logging.level.org.springframework.cloud.sleuth: debug
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig: debug
spring:
  cloud:
    config:
#      allowOverride: true
      override-system-properties: false
#    zookeeper.discovery.instanceIpAddress: 127.0.0.1
  kafka.bootstrap-servers: 127.0.0.1:9092

eureka.instance.hostname: 127.0.0.1

feign.hystrix.enabled: true

all-services: org.ileler.service1,org.ileler.service2

batch:
  config:
    services: ${all-services}
    - key-pattern: $sid.ribbon.NFLoadBalancerRuleClassName
      value: org.ileler.utils.ribbon.DebugRule