server:
  port: 10003
management.metrics.web.server.auto-time-requests: false
zipkin:
  collector.kafka.bootstrap-servers: ${spring.kafka.bootstrap-servers:}
  storage:
    type: elasticsearch
    elasticsearch.hosts: ${es.hosts:}