logging.level.root: info
logging.level.org.ileler: debug
eureka.server:
  enable-self-preservation: false
  eviction-interval-timer-in-ms: 30000

logging.level.com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient: debug