server:
  port: 11001
logging.level.root: error
#logging.level.com.netflix.discovery: debug
spring:
  zipkin:
    sender.type: web
    base-url: http://localhost:10003
  sleuth.sampler.percentage: 1.0
  cloud:
    service-registry:
      auto-registration:
        enabled: true