server:
  port: 11001
logging.level.root: info
logging.level.org.ileler: debug
logging.level.org.springframework.cloud.sleuth: debug
spring:
  zipkin:
    sender.type: web
    base-url: http://localhost:10003
  sleuth.sampler.percentage: 1.0