server:
  port: 11999
logging.level.root: error
logging.level.org.ileler: debug
spring:
  cloud:
    gateway:
      routes:
      - id: openapi
        uri: ${com.mpr.api.gateway:http://localhost}
        predicates:
        - Path=/openapi/**
        filters:
        - StripPrefix=1
      - id: pss
        uri: lb://com.mpr.panmedia.shop
        predicates:
        - Path=/pss/**
        filters:
        - StripPrefix=1
      - id: pgsm
        uri: lb://com.mpr.panmedia.goods.mpr
        predicates:
        - Path=/pgsm/**
        filters:
        - StripPrefix=1
#      - id: index-html
#        predicates:
#        - Path=**/index.html
#        filters:
#        - AddResponseHeader=Cache-Control, no-store
#      - id: static-file
#        uri: file:///data/pub/
#        predicates:
#        - Path=/file/**
#        filters:
#        - StripPrefix=1

gateway:
  static-resource:
  - patterns: /file,/file/,/file/index.htm*
    locations: file:/data/pub/
    default-page: index.html
    cache-control: no-store
  - patterns: /file/**
    locations: file:/data/pub/